# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/csmajs/adist003/final-project-scelo002-nvern003-adist003-ogodh001/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/csmajs/adist003/final-project-scelo002-nvern003-adist003-ogodh001/src

# Include any dependencies generated for this target.
include CMakeFiles/../Time_Managment.exe.dir/depend.make
# Include any dependencies generated by the compiler for this target.
include CMakeFiles/../Time_Managment.exe.dir/compiler_depend.make

# Include the progress variables for this target.
include CMakeFiles/../Time_Managment.exe.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/../Time_Managment.exe.dir/flags.make

CMakeFiles/../Time_Managment.exe.dir/main.cpp.o: CMakeFiles/../Time_Managment.exe.dir/flags.make
CMakeFiles/../Time_Managment.exe.dir/main.cpp.o: main.cpp
CMakeFiles/../Time_Managment.exe.dir/main.cpp.o: CMakeFiles/../Time_Managment.exe.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/csmajs/adist003/final-project-scelo002-nvern003-adist003-ogodh001/src/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/../Time_Managment.exe.dir/main.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/../Time_Managment.exe.dir/main.cpp.o -MF CMakeFiles/../Time_Managment.exe.dir/main.cpp.o.d -o CMakeFiles/../Time_Managment.exe.dir/main.cpp.o -c /home/csmajs/adist003/final-project-scelo002-nvern003-adist003-ogodh001/src/main.cpp

CMakeFiles/../Time_Managment.exe.dir/main.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../Time_Managment.exe.dir/main.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/csmajs/adist003/final-project-scelo002-nvern003-adist003-ogodh001/src/main.cpp > CMakeFiles/../Time_Managment.exe.dir/main.cpp.i

CMakeFiles/../Time_Managment.exe.dir/main.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../Time_Managment.exe.dir/main.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/csmajs/adist003/final-project-scelo002-nvern003-adist003-ogodh001/src/main.cpp -o CMakeFiles/../Time_Managment.exe.dir/main.cpp.s

CMakeFiles/../Time_Managment.exe.dir/TaskList.cpp.o: CMakeFiles/../Time_Managment.exe.dir/flags.make
CMakeFiles/../Time_Managment.exe.dir/TaskList.cpp.o: TaskList.cpp
CMakeFiles/../Time_Managment.exe.dir/TaskList.cpp.o: CMakeFiles/../Time_Managment.exe.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/csmajs/adist003/final-project-scelo002-nvern003-adist003-ogodh001/src/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building CXX object CMakeFiles/../Time_Managment.exe.dir/TaskList.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/../Time_Managment.exe.dir/TaskList.cpp.o -MF CMakeFiles/../Time_Managment.exe.dir/TaskList.cpp.o.d -o CMakeFiles/../Time_Managment.exe.dir/TaskList.cpp.o -c /home/csmajs/adist003/final-project-scelo002-nvern003-adist003-ogodh001/src/TaskList.cpp

CMakeFiles/../Time_Managment.exe.dir/TaskList.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../Time_Managment.exe.dir/TaskList.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/csmajs/adist003/final-project-scelo002-nvern003-adist003-ogodh001/src/TaskList.cpp > CMakeFiles/../Time_Managment.exe.dir/TaskList.cpp.i

CMakeFiles/../Time_Managment.exe.dir/TaskList.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../Time_Managment.exe.dir/TaskList.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/csmajs/adist003/final-project-scelo002-nvern003-adist003-ogodh001/src/TaskList.cpp -o CMakeFiles/../Time_Managment.exe.dir/TaskList.cpp.s

CMakeFiles/../Time_Managment.exe.dir/AwardList.cpp.o: CMakeFiles/../Time_Managment.exe.dir/flags.make
CMakeFiles/../Time_Managment.exe.dir/AwardList.cpp.o: AwardList.cpp
CMakeFiles/../Time_Managment.exe.dir/AwardList.cpp.o: CMakeFiles/../Time_Managment.exe.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/csmajs/adist003/final-project-scelo002-nvern003-adist003-ogodh001/src/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building CXX object CMakeFiles/../Time_Managment.exe.dir/AwardList.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/../Time_Managment.exe.dir/AwardList.cpp.o -MF CMakeFiles/../Time_Managment.exe.dir/AwardList.cpp.o.d -o CMakeFiles/../Time_Managment.exe.dir/AwardList.cpp.o -c /home/csmajs/adist003/final-project-scelo002-nvern003-adist003-ogodh001/src/AwardList.cpp

CMakeFiles/../Time_Managment.exe.dir/AwardList.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../Time_Managment.exe.dir/AwardList.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/csmajs/adist003/final-project-scelo002-nvern003-adist003-ogodh001/src/AwardList.cpp > CMakeFiles/../Time_Managment.exe.dir/AwardList.cpp.i

CMakeFiles/../Time_Managment.exe.dir/AwardList.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../Time_Managment.exe.dir/AwardList.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/csmajs/adist003/final-project-scelo002-nvern003-adist003-ogodh001/src/AwardList.cpp -o CMakeFiles/../Time_Managment.exe.dir/AwardList.cpp.s

# Object files for target ../Time_Managment.exe
__/Time_Managment_exe_OBJECTS = \
"CMakeFiles/../Time_Managment.exe.dir/main.cpp.o" \
"CMakeFiles/../Time_Managment.exe.dir/TaskList.cpp.o" \
"CMakeFiles/../Time_Managment.exe.dir/AwardList.cpp.o"

# External object files for target ../Time_Managment.exe
__/Time_Managment_exe_EXTERNAL_OBJECTS =

../Time_Managment.exe: CMakeFiles/../Time_Managment.exe.dir/main.cpp.o
../Time_Managment.exe: CMakeFiles/../Time_Managment.exe.dir/TaskList.cpp.o
../Time_Managment.exe: CMakeFiles/../Time_Managment.exe.dir/AwardList.cpp.o
../Time_Managment.exe: CMakeFiles/../Time_Managment.exe.dir/build.make
../Time_Managment.exe: CMakeFiles/../Time_Managment.exe.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/home/csmajs/adist003/final-project-scelo002-nvern003-adist003-ogodh001/src/CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Linking CXX executable ../Time_Managment.exe"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/../Time_Managment.exe.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/../Time_Managment.exe.dir/build: ../Time_Managment.exe
.PHONY : CMakeFiles/../Time_Managment.exe.dir/build

CMakeFiles/../Time_Managment.exe.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/../Time_Managment.exe.dir/cmake_clean.cmake
.PHONY : CMakeFiles/../Time_Managment.exe.dir/clean

CMakeFiles/../Time_Managment.exe.dir/depend:
	cd /home/csmajs/adist003/final-project-scelo002-nvern003-adist003-ogodh001/src && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/csmajs/adist003/final-project-scelo002-nvern003-adist003-ogodh001/src /home/csmajs/adist003/final-project-scelo002-nvern003-adist003-ogodh001/src /home/csmajs/adist003/final-project-scelo002-nvern003-adist003-ogodh001/src /home/csmajs/adist003/final-project-scelo002-nvern003-adist003-ogodh001/src /home/csmajs/adist003/final-project-scelo002-nvern003-adist003-ogodh001/src/Time_Managment.exe.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/../Time_Managment.exe.dir/depend

