# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001

# Include any dependencies generated for this target.
include src/CMakeFiles/../Time_Management.exe.dir/depend.make
# Include any dependencies generated by the compiler for this target.
include src/CMakeFiles/../Time_Management.exe.dir/compiler_depend.make

# Include the progress variables for this target.
include src/CMakeFiles/../Time_Management.exe.dir/progress.make

# Include the compile flags for this target's objects.
include src/CMakeFiles/../Time_Management.exe.dir/flags.make

src/CMakeFiles/../Time_Management.exe.dir/main.cpp.o: src/CMakeFiles/../Time_Management.exe.dir/flags.make
src/CMakeFiles/../Time_Management.exe.dir/main.cpp.o: src/main.cpp
src/CMakeFiles/../Time_Management.exe.dir/main.cpp.o: src/CMakeFiles/../Time_Management.exe.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object src/CMakeFiles/../Time_Management.exe.dir/main.cpp.o"
	cd /home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001/src && /usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT src/CMakeFiles/../Time_Management.exe.dir/main.cpp.o -MF CMakeFiles/../Time_Management.exe.dir/main.cpp.o.d -o CMakeFiles/../Time_Management.exe.dir/main.cpp.o -c /home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001/src/main.cpp

src/CMakeFiles/../Time_Management.exe.dir/main.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../Time_Management.exe.dir/main.cpp.i"
	cd /home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001/src && /usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001/src/main.cpp > CMakeFiles/../Time_Management.exe.dir/main.cpp.i

src/CMakeFiles/../Time_Management.exe.dir/main.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../Time_Management.exe.dir/main.cpp.s"
	cd /home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001/src && /usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001/src/main.cpp -o CMakeFiles/../Time_Management.exe.dir/main.cpp.s

src/CMakeFiles/../Time_Management.exe.dir/TaskList.cpp.o: src/CMakeFiles/../Time_Management.exe.dir/flags.make
src/CMakeFiles/../Time_Management.exe.dir/TaskList.cpp.o: src/TaskList.cpp
src/CMakeFiles/../Time_Management.exe.dir/TaskList.cpp.o: src/CMakeFiles/../Time_Management.exe.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building CXX object src/CMakeFiles/../Time_Management.exe.dir/TaskList.cpp.o"
	cd /home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001/src && /usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT src/CMakeFiles/../Time_Management.exe.dir/TaskList.cpp.o -MF CMakeFiles/../Time_Management.exe.dir/TaskList.cpp.o.d -o CMakeFiles/../Time_Management.exe.dir/TaskList.cpp.o -c /home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001/src/TaskList.cpp

src/CMakeFiles/../Time_Management.exe.dir/TaskList.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../Time_Management.exe.dir/TaskList.cpp.i"
	cd /home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001/src && /usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001/src/TaskList.cpp > CMakeFiles/../Time_Management.exe.dir/TaskList.cpp.i

src/CMakeFiles/../Time_Management.exe.dir/TaskList.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../Time_Management.exe.dir/TaskList.cpp.s"
	cd /home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001/src && /usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001/src/TaskList.cpp -o CMakeFiles/../Time_Management.exe.dir/TaskList.cpp.s

src/CMakeFiles/../Time_Management.exe.dir/AwardList.cpp.o: src/CMakeFiles/../Time_Management.exe.dir/flags.make
src/CMakeFiles/../Time_Management.exe.dir/AwardList.cpp.o: src/AwardList.cpp
src/CMakeFiles/../Time_Management.exe.dir/AwardList.cpp.o: src/CMakeFiles/../Time_Management.exe.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building CXX object src/CMakeFiles/../Time_Management.exe.dir/AwardList.cpp.o"
	cd /home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001/src && /usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT src/CMakeFiles/../Time_Management.exe.dir/AwardList.cpp.o -MF CMakeFiles/../Time_Management.exe.dir/AwardList.cpp.o.d -o CMakeFiles/../Time_Management.exe.dir/AwardList.cpp.o -c /home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001/src/AwardList.cpp

src/CMakeFiles/../Time_Management.exe.dir/AwardList.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../Time_Management.exe.dir/AwardList.cpp.i"
	cd /home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001/src && /usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001/src/AwardList.cpp > CMakeFiles/../Time_Management.exe.dir/AwardList.cpp.i

src/CMakeFiles/../Time_Management.exe.dir/AwardList.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../Time_Management.exe.dir/AwardList.cpp.s"
	cd /home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001/src && /usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001/src/AwardList.cpp -o CMakeFiles/../Time_Management.exe.dir/AwardList.cpp.s

# Object files for target ../Time_Management.exe
__/Time_Management_exe_OBJECTS = \
"CMakeFiles/../Time_Management.exe.dir/main.cpp.o" \
"CMakeFiles/../Time_Management.exe.dir/TaskList.cpp.o" \
"CMakeFiles/../Time_Management.exe.dir/AwardList.cpp.o"

# External object files for target ../Time_Management.exe
__/Time_Management_exe_EXTERNAL_OBJECTS =

bin/../Time_Management.exe: src/CMakeFiles/../Time_Management.exe.dir/main.cpp.o
bin/../Time_Management.exe: src/CMakeFiles/../Time_Management.exe.dir/TaskList.cpp.o
bin/../Time_Management.exe: src/CMakeFiles/../Time_Management.exe.dir/AwardList.cpp.o
bin/../Time_Management.exe: src/CMakeFiles/../Time_Management.exe.dir/build.make
bin/../Time_Management.exe: src/CMakeFiles/../Time_Management.exe.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001/CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Linking CXX executable ../bin/../Time_Management.exe"
	cd /home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001/src && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/../Time_Management.exe.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
src/CMakeFiles/../Time_Management.exe.dir/build: bin/../Time_Management.exe
.PHONY : src/CMakeFiles/../Time_Management.exe.dir/build

src/CMakeFiles/../Time_Management.exe.dir/clean:
	cd /home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001/src && $(CMAKE_COMMAND) -P CMakeFiles/../Time_Management.exe.dir/cmake_clean.cmake
.PHONY : src/CMakeFiles/../Time_Management.exe.dir/clean

src/CMakeFiles/../Time_Management.exe.dir/depend:
	cd /home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001 && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001 /home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001/src /home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001 /home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001/src /home/csmajs/ogodh001/final-project-scelo002-nvern003-adist003-ogodh001/src/Time_Management.exe.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : src/CMakeFiles/../Time_Management.exe.dir/depend

